apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: solution0005
  description: solution0005
  links:
    - url: https://solution0005-dev.ea.sdlc.k8s.cbrands.com/testcontext/api/message
      title: Solution API
      icon: dashboard
  annotations:
    github.com/project-slug: ConstellationBrands/solution0005
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: "app=solution0005"
    argocd/app-selector: "app=solution0005"
    jira/project-key: 
    #circleci.com/project-slug: github/ConstellationBrands/solution0005
    #jira/component: <example-component>
spec:
  type: service
  lifecycle: experimental
  owner: ConstellationBrands
  providesApis:
    - solution0005
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: solution0005
  description: solution0005
spec:
  type: openapi
  lifecycle: experimental
  owner: ConstellationBrands
  definition:
    $text: https://github.com/ConstellationBrands/solution0005/blob/main/swagger.yaml